### PR TITLE
Add integration test for supporting fluentd target client auth in logging

### PR DESCRIPTION
**Pull request by aiwantaozi**
Issue:
https://github.com/rancher/rancher/issues/18438

Related rancher PR:
https://github.com/rancher/rancher/pull/18442

### CODE REVIEW

**Comment by bmdepesa** [comment]
@aiwantaozi is this still WIP? or ready to be reviewed/merged?

**Comment by aiwantaozi** [comment]
It's ready to be reviewed, but now seem like we move to validation test to rancher/rancher repo, I will move the pr there.

**Comment by loganhz** [comment]
Please move this into rancher/rancher

**Comment by aiwantaozi** [comment]
already in rancher's pr list

**Pull request closed without merging**
